### ISSUE TITLE
Wrong package on PyPi

### ISSUE THREAD

**Issue by bashu** [ixc/django-model-settings#18]
Hey,

Command:

```pip install -U django-model-settings```

Output:
```shell
Collecting django-model-settings
  Downloading django_model_settings-0.3-py2.py3-none-any.whl
Installing collected packages: django-model-settings
Successfully installed django-model-settings-0.3
```

Python Shell:
```python
>>> from model_settings import utils
>>> utils.get_all_related_objects
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'get_all_related_objects'
```
Can you create correct python package and re-upload it on PyPi, e.g:
```shell
python setup.py sdist bdist_wheel upload
```

It seems you have uploaded content of outdated "develop" branch rather than "master"

**Comment by bashu** [comment]
@markfinger o hai, mark

**Comment by bashu** [comment]
@markfinger any news?

**Comment by markfinger** [comment]
Sorry, I'm buried under a mountain of work at the moment. It's on my todo list and I will get around to it, just can't guarantee any earlier than next week.

**Comment by bashu** [comment]
@markfinger glad to know, thanks!

**Comment by markfinger** [comment]
@bashu I've just pushed `django-model-settings==0.3.1`

**Comment by markfinger** [comment]
Not sure how the 0.3.0 release was so messed up 😕 

Oh wells. Let me know if it works for you 😄

**Comment by bashu** [comment]
@markfinger it's working
